---
  name: Install & Start Apache2, The Reboot server
  hosts: Webserver
  become: yes
  become_user: web_admin
  tasks:
      - name: Install Apache2 in the server
        yum:
          service: httpd
          state: present

      - name: Start Apache2 in server
        shell:
            service: httpd
            state: started

      - name: Restart server
        shell: reboot

      - name: Wait for the machine to come back online
        wait_for_connection:
            connect_timeout: 60
            sleep: 5
            delay: 5
            timeout: 300
        notify:
        - Start apache

  handlers:
    - name: Start apache
      ansible.builtin.service:
        name: httpd
        state: started


