version: '3.1'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports: 
      - 80:80
    volumes:
      - ./www:/var/www/html
  httpd:
    image: httpd:2.4
    restart: always
    ports: 
      - 8080:80
    volumes:
      - ./www:/var/www/html
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/   
    


# to stop all the running coatiner : docker stop $(docker ps)
# to remove all the conatiners : docker rm $(docker ps -a)