- name: Start httpd
  service:
    name: httpd
    state: started

- name: Start apache2
  service:
    name: apache2
    state: started

- name: Restart httpd
  service:
    name: httpd
    state: restarted

- name: Restart apache2
  service:
    name: apache2
    state: restarted